### ISSUE TITLE
No failure if dir doesnt exist

### ISSUE THREAD

**Issue by jayvdb** [pytest-dev/nose2pytest#12]
If the directory given in the arguments does not exist, the program should have a non-zero exit status.

**Comment by PhilippSelenium** [comment]
Looking at the code this seems to be an issue of lib2to3:

In https://github.com/pytest-dev/nose2pytest/blob/b5f76c57aee837c7c84a4787efd5daa310183cf4/nose2pytest/script.py#L595
the directory name is directly passed to ```NoseConversionRefactoringTool``` which inherits from ```lib2to3refactor.MultiprocessRefactoringTool```

But of course it could also be hacked in here.

**Comment by jayvdb** [comment]
I guess we can check `args.dir_name` before passing it to lib2to3
