### ISSUE TITLE
ParseError: bad input: type=6, value=''

### ISSUE THREAD

**Issue by jayvdb** [pytest-dev/nose2pytest#14]
Caused by https://github.com/spulec/moto/blob/master/tests/test_batch/test_batch.py

```py
Traceback (most recent call last):
  File "/usr/bin/nose2pytest", line 11, in <module>
    load_entry_point('nose2pytest==1.0.8', 'console_scripts', 'nose2pytest')()
  File "/usr/lib/python3.8/site-packages/nose2pytest/script.py", line 595, in main
    refac.refactor_dir(args.dir_name, write=args.write)
  File "/usr/lib64/python3.8/lib2to3/refactor.py", line 300, in refactor_dir
    self.refactor_file(fullname, write, doctests_only)
  File "/usr/lib64/python3.8/lib2to3/refactor.py", line 727, in refactor_file
    return super(MultiprocessRefactoringTool, self).refactor_file(
  File "/usr/lib64/python3.8/lib2to3/refactor.py", line 335, in refactor_file
    tree = self.refactor_string(input, filename)
  File "/usr/lib64/python3.8/lib2to3/refactor.py", line 360, in refactor_string
    self.log_error("Can't parse %s: %s: %s",
  File "/usr/lib64/python3.8/lib2to3/refactor.py", line 358, in refactor_string
    tree = self.driver.parse_string(data)
  File "/usr/lib64/python3.8/lib2to3/pgen2/driver.py", line 103, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/usr/lib64/python3.8/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/usr/lib64/python3.8/lib2to3/pgen2/parse.py", line 162, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=6, value='', context=('\n    ', (19, 4))
```

**Comment by PhilippSelenium** [comment]
@jayvdb I cannot reproduce this error. Can you post the cmd you executed and the version of nose2pytest?

**Comment by jayvdb** [comment]
The mentioned file has changed since I created the issue.

https://github.com/spulec/moto/blob/master@%7B2020-08-17T13:52:32Z%7D/tests/test_batch/test_batch.py  is the version when I encountered the error.  Did you try that version?

**Comment by PhilippSelenium** [comment]
I tried also that version and ran ```nose2pytest``` on the whole folder:  No errors but also no changes.

**Comment by EwoutH** [comment]
I have a similar issue, using on [this](https://github.com/EwoutH/EMAworkbench/blob/de0fb1e3909269208ba45ab7f5ca85ce57e42b18/.github/workflows/nose2pytest.yml) CI setup ([log](https://github.com/EwoutH/EMAworkbench/runs/6490638863?check_suite_focus=true#step:6:29)):
```
lib2to3.pgen2.parse.ParseError: bad input: type=3, value='"file-open {fn} file-write {variable}"', context=('', (202, 23))
```

**Comment by schollii** [comment]
@EwoutH I do not recommend using this library the way you do in the CI: this means 2 years from now you could still be using it, through new versions of python, pytest, nose, etc. Instead, do the conversion once, and discard nose2pytest.

**Comment by schollii** [comment]
The lib2to3 that is used has been deprecated as it is known to not support all syntax of Python 3.10+ (but supports 99%). This is likely the cause. 

If this is the case, you will have to find the code in your test suite that causes lib2to3 to fail parsing, comment it out, do the conversion, then uncomment it (and fix any nose-isms left in it).
