### ISSUE TITLE
Replace lib2to3 with fissix

### ISSUE THREAD

**Issue by jayvdb** [pytest-dev/nose2pytest#16]
https://github.com/jreese/fissix is a maintained library derived from lib2to3.

https://github.com/PyCQA/modernize recently switched to using fissix.

**Comment by jayvdb** [comment]
This would be the end of https://github.com/pytest-dev/nose2pytest/issues/4

**Comment by dosas** [comment]
Using fissix would require us to drop support for py34 and py35 but since the are EOL I think taht would be okay?

**Comment by schollii** [comment]
3.4 already dropped. Dropping 3.5 fine too.

**Comment by schollii** [comment]
However, from the `2to3` docs on python website: 

> Python 3.9 switched to a PEG parser (see [PEP 617](https://peps.python.org/pep-0617/)) while lib2to3 is using a less flexible LL(1) parser. Python 3.10 includes new language syntax that is not parsable by lib2to3’s LL(1) parser (see [PEP 634](https://peps.python.org/pep-0634/)).

This indicates that lib2to3, or fissix, may not be able to parse some Python code, starting with Python 3.10. Although it is likely that in the context of tests, this will not be an issue for another while. 

I will leave this issue open until 3.13 removes it. But most likely, it will simply be necessary to use 3.12 or earlier: the version of python used to run the conversion script is independent of the version used to run a user's test suite with pytest and even moreso to run the user's app being tested by the test suite. 

So I will likely close this issue. Let me know if I'm missing anything.

**Comment by dosas** [comment]
https://github.com/pytest-dev/nose2pytest/pull/17

**Comment by cclauss** [comment]
I believe this issue can be closed.
* #17 (merged)
* https://github.com/amyreese/fissix?tab=readme-ov-file#used-by
