### ISSUE TITLE
Add Python 2.7 support

### ISSUE THREAD

**Issue by dmitrytokarev** [pytest-dev/nose2pytest#4]
As of ver 1.0.8 nose2pytest supports only Python 3.4+.

**Comment by schollii** [comment]
Do you mean that it supported it previously? I am very doubtful, can you provide a sample of the code that you used?

**Comment by dmitrytokarev** [comment]
It didn't support 2.7 before. We thought to use this lib in our org, but we only run 2.7 for now. We can just leave this issue open for now, to see if anyone else is interested in 2.7 support. And if there will be little interest - just close this issue, since the effort may not be worth it.

**Comment by cclauss** [comment]
Can we close this issue?

**Comment by nicoddemus** [comment]
Yes, thanks for the ping. 👍
