### ISSUE TITLE
almost equal

### ISSUE THREAD

**Issue by massich** [pytest-dev/nose2pytest#5]
Right now  `assert_almost_equal(a,b, delta[, msg])` is translated to `assert abs(a - b) <= delta[, msg] `. Shouldn't it be translated to `assert a == approx(b) [, msg]` based on [this](https://github.com/pytest-dev/pytest/pull/1441)

I can make a PR if needed.

**Comment by schollii** [comment]
Thanks for bringing this up and offering to make a PR. 

From the description at pytest's [python_api.py](https://github.com/pytest-dev/pytest/blob/539523cfee4c49a765569abcf68134b1255eedb5/_pytest/python_api.py), the translation should be to `assert a == approx(b, rel=0, abs=delta)` (although it might be to `assert a == approx(b, rel=delta, abs=0)`, we'd have to verify which one is correct). 

However,  `nose.tools.assert_almost_equal` (itself `unittest.TestCase.assertAlmostEqual`) is symmetrical in a and b whereas `approx` is not, and there is no guarantee that the user put the expected value in b. I suppose that in many cases, this would not matter. Note BTW that the doc in python_api.py about `unittest.TestCase.assertAlmostEqual` is incorrect, the absolute delta is configurable.

If you can investigate and report back on when the difference matters (small delta? is it rel or abs that must be set in approx), I will be glad to merge your PR, which should include a note in the readme about when differences matter.

**Comment by massich** [comment]
pytest approx ends up calling `return abs(self.expected - actual) <= self.tolerance` ([here](https://github.com/pytest-dev/pytest/blob/539523cfee4c49a765569abcf68134b1255eedb5/_pytest/python_api.py#L209)). Which is the same as nose does: 
```sh
In [2]: nose.tools.assert_almost_equal??
Signature: nose.tools.assert_almost_equal(first, second, places=None, msg=None, delta=None)
Source:   
    def assertAlmostEqual(self, first, second, places=None, msg=None,
                          delta=None):
        """Fail if the two objects are unequal as determined by their
           difference rounded to the given number of decimal places
           (default 7) and comparing to zero, or by comparing that the
           between the two objects is more than the given delta.

           Note that decimal places (from zero) are usually not the same
           as significant digits (measured from the most significant digit).

           If the two objects compare equal then they will automatically
           compare almost equal.
        """
        if first == second:
            # shortcut
            return
        if delta is not None and places is not None:
            raise TypeError("specify delta or places not both")

        if delta is not None:
            if abs(first - second) <= delta:
                return

            standardMsg = '%s != %s within %s delta' % (safe_repr(first),
                                                        safe_repr(second),
                                                        safe_repr(delta))
        else:
            if places is None:
                places = 7

            if round(abs(second-first), places) == 0:
                return

            standardMsg = '%s != %s within %r places' % (safe_repr(first),
                                                          safe_repr(second),
                                                          places)
        msg = self._formatMessage(msg, standardMsg)
        raise self.failureException(msg)
File:      ~/miniconda3/lib/python3.6/unittest/case.py
Type:      method
```
And based on [this comment](https://github.com/pytest-dev/pytest/blob/539523cfee4c49a765569abcf68134b1255eedb5/_pytest/python_api.py#L237) I think we should translate to `assert a == approx(b, abs=delta)`

**Comment by schollii** [comment]
Indeed. 

Looks like approx was introduced in 3.0? This will impose a restriction on pytest version usable with result of nose2pytest (if assertAlmostEqual is used). It would be good to have a custom command line option "--no-approx" (or similar, maybe there is a better name) to use the current conversion for assert_almost_equal. 

A unit test should verify with a few different combinations of actual vs expected vs delta that the two expressions are equivalent. 

I am not in a position to make these changes soon, so a PR would be most welcome.

**Comment by nicoddemus** [comment]
> It would be good to have a custom command line option "--no-approx" (or similar, maybe there is a better name) to use the current conversion for assert_almost_equal.

Alternatively, using something based on pytest version might be more future proof. For example, `--max-pytest-version=3.0` would use only features available to `pytest-3.0` or lower, `--max-pytest-version=3.1` to features available to `pytest-3.1` or lower and so on.

I'm curious, is there a high demand from people to keep compatibility with older versions (say people stuck in 2.X unable to upgrade to 3.0)?

**Comment by massich** [comment]
my idea was to update [these lines](https://github.com/pytest-dev/nose2pytest/blob/master/nose2pytest/script.py#L509) let everything break and fix it. But being able to do both transformations might need some more insides about nose2pytest than I thought. So I would appreciate any pointers or where the parameter should be added or how can i test for both behaviours. 

A summary of how would you target the feature it would be really helpful.

**Comment by nicoddemus** [comment]
IMHO it is sensible for a conversion tool to convert to the latest version unless compatibility with old versions is something explicitly required by users, which is why I asked if that is an actual demand.

**Comment by nicoddemus** [comment]
Of course, that's entirely @schollii's call. 😁

**Comment by schollii** [comment]
@nicoddemus:
There hasn't been an actual demand, but there hasn't been any
request-for-input from end-users of the tool, either :)
Since it would be very easy to retrofit such a command line setting on
nose2pytest script, we can go ahead, and see if anyone complains, fair?

**Comment by schollii** [comment]
@massich: 
Those are the correct lines. The almost_equal line would become something like

    assert_almost_equal='a == approx(b, abs=delta)'

whereas for the not-almost-equal, the following might work: 

    assert_not_almost_equal='a != approx(b, abs=delta)'

If not, this should work (not as nice): 

    assert_not_almost_equal='not (a == approx(b, abs=delta))'

**Comment by nicoddemus** [comment]
> Since it would be very easy to retrofit such a command line setting on
nose2pytest script, we can go ahead, and see if anyone complains, fair?

Definitely. 😁
